- name: Copy Redis repo file
  ansible.builtin.template:
    src: redis.repo
    dest: /etc/yum.repos.d/redis.repo

- name: Install the redis
  ansible.builtin.yum:
    name: redis.7.0.9-1
    state: installed

#- name: Configure Redis YUM repos
#  ansible.builtin.dnf:
#    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
#    state: installed
#    disable_gpg_check: yes
#
#- name: Configure Redis 6.2
#  ansible.builtin.shell: dnf module enable redis:remi-6.2 -y
#
#- name: Install Redis
#  ansible.builtin.dnf:
#    name:
#      - redis
#    state: installed
#    disable_gpg_check: yes

- name: replace listening ip address
  ansible.builtin.replace:
    path: "{{item}}"
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  loop:
    - /etc/redis.conf
    - /etc/redis/redis.conf

- name: start redis service
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: yes
