- name: Install the nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: include from the common
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Copy RoboShop Config file
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Copy nginx Config file
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf


- name: Start Nginx Service
  ansible.builtin.systemd:
    name: nginx
    state: restartedls
    
    enabled: yes