- name: Prometheus Server Configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Restart Prometheus server
  ansible.builtin.systemd:
    name: prometheus
    state: restarted