- name: create user
  ansible.builtin.user:
    name: roboshop
  register: app_user

- name: Remove directory
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}"
    state: absent

- name: create directory
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}"
    state: directory

- name: download and unzip the file
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/{{ COMPONENT }}/archive/main.zip
    dest: /tmp
    remote_src: yes


- name: Copy {{ COMPONENT }} Code to App Location
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/{{SUFFIX}}
    dest: "{{ APP_LOCATION }}/"
    remote_src: yes
