- name: set hostname
  ansible.builtin.shell: set-hostname {{ COMPONENT }}

- name: install python modules for aws secret manager
  ansible.builtin.pip:
    name:
      - boto3
      - botocore

    executable: pip3