- name: setup yum repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_16.x | sudo bash -

- name: Install the nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: include app setup from the common
  ansible.builtin.include_role:
    name: common
    tasks_from: download

# these steps are coming from CI steps
#- name: downloading npm dependicices
#  community.general.npm:
#    path: "{{ APP_LOCATION }}"

- name: setup {{ COMPONENT }} systemd service
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd

- name: setup filebeat
  ansible.builtin.include_role:
    name: elk
    tasks_from: filebeat

